name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request: 
    branches: [ "dev" ]  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
         name: Checkout
         uses: actions/checkout@v3
      -
         name: Login to Docker Hub
         uses: docker/login-action@v1
         with: 
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
          name: Set up Docker Buildx 
          uses: docker/setup-buildx-action@v1
          with: 
            context: .
            file: ./server/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/todoapp:latest
     
            

